FROM node:20-slim

WORKDIR /app

RUN corepack enable

COPY packages/web/package.json packages/web/pnpm-lock.yaml /app/packages/web/

WORKDIR /app/packages/web

RUN pnpm install --frozen-lockfile

COPY packages/web /app/packages/web

EXPOSE 8000

CMD ["pnpm", "start"]
